---
title: "Preprocessing"
output: html_document
---

```{r, warning=F, message=F, include=F}
getwd()
setwd("/Users/asmaareda/Science/1python/22_EG_combio_Diploma/*1_Publication_Asmaa/EGCompBio_Papers/1_Sarah_R/Datasets/GSE60427")
getwd()

```

#### Load The required Libraries
```{r, warning=F, message=F}
library(GEOquery)
library(limma)
library(readxl)
library(dplyr)
library(tidyverse)
library(pheatmap)
library(affy)
library(affyPLM)
library(hgu133plus2.db)
library(EnhancedVolcano)
library(ggplot2)
library(ggVennDiagram)
library(DT) 
library(plotly)
#library(rgl)
library(EnhancedVolcano)
```



```{r}
filtered_num_mat = read.csv('filtered_num_mat.csv', row.names = 1)
exp_log = log2(filtered_num_mat + 1)

exp_scaled_t = scale(t(exp_log))
exp_scaled = t(exp_scaled_t)

```


#### Preprocssing analysis
```{r}
options(repr.plot.width = 10, repr.plot.height = 8)
par(mar = c(8, 5, 2, 2), mfrow = c(1, 3))  # Adjust margins and set layout

# Boxplot: Before Normalization
boxplot(
  filtered_num_mat[, 1:12], 
  main = "Before Normalization", 
  horizontal = TRUE, 
  names = colnames(filtered_num_mat)[1:12], 
  las = 2,
  col = "lightgreen",
  cex.main = 1.5,           
  font.main = 2,            
  cex.axis = 1.2,           
  font.axis = 2             
)

# Boxplot: After Normalization
boxplot(
  exp_log[, 1:12], 
  main = "After Normalization", 
  horizontal = TRUE, 
  names = colnames(exp_log)[1:12], 
  las = 2,
  col = "lightgreen",
  cex.main = 1.5,           
  font.main = 2,            
  cex.axis = 1.2,           
  font.axis = 2             
)

# Boxplot: After Scaling
boxplot(
  exp_scaled[, 1:12], 
  main = "After Scaling", 
  horizontal = TRUE, 
  names = colnames(exp_scaled)[1:12], 
  las = 2,
  col = "lightgreen",
  cex.main = 1.5,           
  font.main = 2,            
  cex.axis = 1.2,           
  font.axis = 2             
)
```