---
title: "DEGs"
output: html_document
---

```{r, warning=F, message=F, include=F}
getwd()
setwd("/Users/asmaareda/Science/1python/22_EG_combio_Diploma/*1_Publication_Asmaa/EGCompBio_Papers/1_Sarah_R/Datasets/GSE60427")
getwd()
list.files()
```

### Load The required Libraries
```{r, warning=F, message=F}
library(GEOquery)
library(limma)
library(readxl)
library(dplyr)
library(tidyverse)
library(pheatmap)
library(affy)
library(affyPLM)
library(hgu133plus2.db)
library(EnhancedVolcano)
library(ggplot2)
library(ggVennDiagram)
library(DT) 
library(plotly)
#library(rgl)
library(EnhancedVolcano)
```

```{r}
filtered_num_mat = read.csv('filtered_num_mat.csv', row.names = 1)
exp_log = log2(filtered_num_mat + 1)

exp_scaled_t = scale(t(exp_log))
exp_scaled = t(exp_scaled_t)

```

```{r}
metadata = read.csv('gitHubData/metadata_GSE60427.csv')
```

### DEGs
```{r}
unique(metadata$condition)  

selected_metadata2 = metadata[metadata$condition %in% c("H.P_Infection", "Control"), ]
dim(selected_metadata2)    

selected_columns2 = colnames(exp_scaled)[colnames(exp_scaled) %in% selected_metadata2$ID]

filtered_data_scaled2 = exp_scaled[, selected_columns2]
dim(filtered_data_scaled2)     
```

```{r}
unique(selected_metadata2$condition)    

design = model.matrix(~ 0 + condition, data = selected_metadata2)

colnames(design) <- gsub("condition", "", colnames(design))

unique(selected_metadata2$condition)

# Fit the model
fit = lmFit(filtered_data_scaled2, design)

# Create contrasts for differential expression 
contrast_matrix = makeContrasts(H.PyloriInfection_Vs_Control = H.P_Infection - Control, levels = design)

# Apply contrasts
fit2 = contrasts.fit(fit, contrast_matrix)

# Perform empirical Bayes moderation
fit2 = eBayes(fit2)
```

```{r}
results_H.PyloriInfection_Vs_Control = topTable(fit2, adjust.method = "fdr", number = Inf, sort.by = "p")

# View top DEGs
results_H.PyloriInfection_Vs_Control
```