---
title: "VP"
output: html_document
---

### Load The required Libraries
```{r, warning=F, message=F}
library(GEOquery)
library(limma)
library(readxl)
library(dplyr)
library(tidyverse)
library(pheatmap)
library(affy)
library(affyPLM)
library(hgu133plus2.db)
library(EnhancedVolcano)
library(ggplot2)
library(ggVennDiagram)
library(DT) 
library(plotly)
#library(rgl)
library(EnhancedVolcano)
```




```{r}
results_H.PyloriInfection_Vs_Control = read.csv("results_H.PyloriInfection_Vs_Control.csv")
```

```{r}
unique(results_H.PyloriInfection_Vs_Control$regulation)

results_H.PyloriInfection_Vs_Control$label <- ifelse(
  results_H.PyloriInfection_Vs_Control$regulation %in% c("Upregulated", "Downregulated"),
  results_H.PyloriInfection_Vs_Control$label,  
  NA
)

# Create the base plot
p <- ggplot(data = results_H.PyloriInfection_Vs_Control,
            aes(x = logFC, y = -log10(P.Value), col = regulation)) +
  geom_point() +
  theme_minimal() +
  geom_vline(xintercept = c(-1, 1), col = "red") +  
  geom_hline(yintercept = -log10(0.05), col = "red") +  
  scale_color_manual(values = c("Downregulated" = "blue", "Upregulated" = "red", "Not_Significant" = "green"))

# Add gene labels for significant genes (avoiding overlap)
p <- p + geom_text(aes(label = label), vjust = 1.5, hjust = 1.5, size = 3, check_overlap = TRUE)

print(p)
```


```{r}
# Create Enhanced Volcano Plot
EnhancedVolcano(
  results_H.PyloriInfection_Vs_Control,
  lab = results_H.PyloriInfection_Vs_Control$label,
  x = 'logFC',
  y = 'P.Value',
  selectLab = c("C4orf7", "CD180", "CD19", "LCN2", "FCRL2", "CR2", "CXCL13", "HLA-DRA",
                "FAM159A", "CXCL2", "ARHGAP6", "NMU", "FABP5", "PIN1", "ETFB", "C8orf67",
                "FAM109B", "XLOC_011064", "LINC00472", "HIST2H2AA4"),
  xlab = bquote(~Log[2]~ 'fold change'),
  ylab = bquote(~-Log[10]~ 'P-value'),
  pCutoff = 0.05,
  FCcutoff = 1,
  pointSize = 4.0,
  labSize = 6.0,
  colAlpha = 1,
  legendPosition = 'right',
  legendLabSize = 12,
  legendIconSize = 4.0,
  drawConnectors = TRUE,
  widthConnectors = 0.75,
  colConnectors = 'black',
  col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
  title = "Volcano Plot: H.Pylori Infection vs Control",
  max.overlaps = 50
)
```


